/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DateSelecter: typeof import('./src/components/dates/DateSelecter.vue')['default']
    EditHorse: typeof import('./src/components/horses/EditHorse.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HorseForm: typeof import('./src/components/horses/HorseForm.vue')['default']
    HorsesOverview: typeof import('./src/components/horses/HorsesOverview.vue')['default']
    HorsesTable: typeof import('./src/components/horses/HorsesTable.vue')['default']
    NewHorse: typeof import('./src/components/horses/NewHorse.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
